import asyncio
from typing import Any
import sys
import os

# Add the parent directory to Python path so we can import from scripts
sys.path.append(os.path.join(os.path.dirname(__file__), ".."))

from arq import Worker, cron
from arq.connections import RedisSettings
from scripts.ingest.seed_db import seed_data
from core.config import get_settings

# A sample background task
async def process_shipment_delay(ctx: dict[str, Any], shipment_id: str) -> None:
    print(f"Background task starting: calculating AI delay for shipment {shipment_id}")
    await asyncio.sleep(2) # Simulate ML inference time
    print(f"Background task finished: shipment {shipment_id}")

# Cron job for generating continuous realistic data
async def continuous_data_generation(ctx: dict[str, Any]) -> None:
    print("Cron Job Triggered: Generating new shipment data...")
    try:
        records = await seed_data(seed_count=1, is_cron=True)
        print("Cron Job: Successfully generated new shipments.")
        for rec in records:
            print(f"Tracking ID Generated by Worker: {rec[1]}")
    except Exception as e:
        print(f"Cron Job Error: Failed to seed data - {e}")

async def startup(ctx: dict[str, Any]) -> None:
    print("ARQ Worker starting up...")

async def shutdown(ctx: dict[str, Any]) -> None:
    print("ARQ Worker shutting down...")

class WorkerSettings:
    redis_settings = RedisSettings.from_dsn(get_settings().redis_url)
    functions = [process_shipment_delay]
    cron_jobs = [
        cron(continuous_data_generation, minute=set(range(0, 60, 10))) # Run every 10 minutes
    ]
    on_startup = startup
    on_shutdown = shutdown

if __name__ == "__main__":
    print("Please run this worker using: arq worker.WorkerSettings")
    sys.exit(1)
