minimumReleaseAgeExclude:
  - '@remotion/bundler@4.0.488'
  - '@remotion/canvas-capture@4.0.488'
  - '@remotion/cli@4.0.488'
  - '@remotion/compositor-darwin-arm64@4.0.488'
  - '@remotion/compositor-darwin-x64@4.0.488'
  - '@remotion/compositor-linux-arm64-gnu@4.0.488'
  - '@remotion/compositor-linux-arm64-musl@4.0.488'
  - '@remotion/compositor-linux-x64-gnu@4.0.488'
  - '@remotion/compositor-linux-x64-musl@4.0.488'
  - '@remotion/compositor-win32-x64-msvc@4.0.488'
  - '@remotion/eslint-config-flat@4.0.488'
  - '@remotion/licensing@4.0.488'
  - '@remotion/media-parser@4.0.488'
  - '@remotion/media-utils@4.0.488'
  - '@remotion/player@4.0.488'
  - '@remotion/renderer@4.0.488'
  - '@remotion/streaming@4.0.488'
  - '@remotion/studio-server@4.0.488'
  - '@remotion/studio-shared@4.0.488'
  - '@remotion/studio@4.0.488'
  - '@remotion/tailwind-v4@4.0.488'
  - '@remotion/timeline-utils@4.0.488'
  - '@remotion/web-renderer@4.0.488'
  - '@remotion/zod-types@4.0.488'
  - remotion@4.0.488
  - '@remotion/media@4.0.488'
  - '@remotion/paths@4.0.488'
  - '@remotion/shapes@4.0.488'
  - '@remotion/transitions@4.0.488'
