"""Jakarta road network graph — lazy-loaded singleton for NSGA-II routing.

Loads a pre-downloaded OSMnx GraphML and provides shortest-path travel time
lookups between arbitrary lat/lng pairs. Falls back to a Haversine-based
estimate with a Jakarta traffic multiplier when the graph file is absent.

The graph file is generated by scripts/setup/download_jakarta_graph.py and
stored at data/templates/jakarta_graph.graphml.
"""
import logging
import math
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

_ROOT = Path(__file__).resolve().parents[3]
_GRAPH_PATH = _ROOT / "data" / "templates" / "jakarta_graph.graphml"

_graph: Any = None
_graph_loaded = False

JAKARTA_AVG_SPEED_KMH = 18.0
HAVERSINE_TRAFFIC_FACTOR = 1.4


def _haversine_km(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
    R = 6371.0
    lat1, lon1, lat2, lon2 = map(math.radians, (lat1, lon1, lat2, lon2))
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    a = math.sin(dlat / 2) ** 2 + math.cos(lat1) * math.cos(lat2) * math.sin(dlon / 2) ** 2
    return 2 * R * math.asin(math.sqrt(a))


def get_graph():
    """Load the Jakarta OSMnx graph, or return None if unavailable."""
    global _graph, _graph_loaded
    if _graph_loaded:
        return _graph
    _graph_loaded = True
    if not _GRAPH_PATH.exists():
        logger.info("Jakarta graph not found at %s — using Haversine fallback", _GRAPH_PATH)
        return None
    try:
        import osmnx as ox
        _graph = ox.load_graphml(_GRAPH_PATH)
        logger.info("Jakarta graph loaded: %d nodes, %d edges", len(_graph.nodes), len(_graph.edges))
    except Exception as exc:
        logger.warning("Failed to load Jakarta graph: %s — using fallback", exc)
        _graph = None
    return _graph


def travel_time_min(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
    """Estimate travel time in minutes between two coordinates.

    Uses OSMnx shortest-path travel_time if the graph is loaded, otherwise
    falls back to Haversine distance with Jakarta traffic factor.
    """
    G = get_graph()
    if G is not None:
        try:
            import osmnx as ox
            import networkx as nx

            orig = ox.nearest_nodes(G, lon1, lat1)
            dest = ox.nearest_nodes(G, lon2, lat2)
            if orig == dest:
                return 1.0
            travel_seconds = nx.shortest_path_length(G, orig, dest, weight="travel_time")
            return max(1.0, travel_seconds / 60.0)
        except Exception:
            pass

    straight_km = _haversine_km(lat1, lon1, lat2, lon2)
    road_km = straight_km * HAVERSINE_TRAFFIC_FACTOR
    return max(1.0, road_km / JAKARTA_AVG_SPEED_KMH * 60.0)


def road_distance_km(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
    """Estimate road distance in km between two coordinates."""
    G = get_graph()
    if G is not None:
        try:
            import osmnx as ox
            import networkx as nx

            orig = ox.nearest_nodes(G, lon1, lat1)
            dest = ox.nearest_nodes(G, lon2, lat2)
            if orig == dest:
                return 0.1
            length_m = nx.shortest_path_length(G, orig, dest, weight="length")
            return max(0.1, length_m / 1000.0)
        except Exception:
            pass

    return _haversine_km(lat1, lon1, lat2, lon2) * HAVERSINE_TRAFFIC_FACTOR
